//BATCH 81
//Kunal Todi 2013B3A7480P
//Anish Shah 2013B1A7856P
//main_driver
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "ast.h"
#include "TypeChecker.h"
#include "SymbolTable.h"
#include "Codegen.h"

int main(int argc,char* argv[])
{
	FILE *fp = fopen(argv[1],"r");
	FILE *outfp=fopen("parsetreeoutfile.txt","w");
	FILE *asm_file=fopen(argv[2],"w");
	codegen_main(fp,asm_file,outfp);
	fclose(fp);
	fclose(asm_file);
	fclose(outfp);

	int option;
	printf("LEVEL 4: Symbol table/ AST/ Semantic Rules/Code generation modules work.\n");
	printf("Press option for the defined task\n1 : For printing the token list (on the console) generated by the lexer.\n2 :For parsing to verify the syntactic correctness of the input source code and to produce parse tree (On Console)\n3 :For printing the Abstract Syntax Tree in appropriate format. Also specify the traversal order at the beginning. (On Console)\n4: For displaying the amount of allocated memory and number of nodes to each of parse tree and abstract syntax tree for the test case used.\n5: For printing the Symbol Table in appropriate format showing all relevant information.\n6: For compiling to verify the syntactic and semantic correctness of the input source code.\n7: For producing assembly code (only when there is no syntactic, semantic or type mismatch errors).\n");
	scanf("%d",&option);
	if(option==1)
	{
		for(int i=0;i<no_of_tokens;i++)
		{
			printf("%s %s %d\n",token_arr[i]->TOKEN_TYPE,token_arr[i]->lexeme,token_arr[i]->line_no);
		}
	}
	else if(option==2)
	{
		if(errors==0)
		{
			printf("Successful Compilation\n");
		}
		else
		{
			int i;
			for(i=0;i<errors;i++)
			{
				printf("%s",error_name[i]);
			}
		}
		int c;
		FILE *file;
		file = fopen("parsetreeoutfile.txt", "r");
		if (file) 
		{
    		while ((c = getc(file)) != EOF)
        		putchar(c);
    		fclose(file);
		}
	}
	else if (option==3)
	{
		print_AST();
		return 0;
	}
	else if(option==4)
	{
		compute_parse_tree_compression();
		return 0;	
	}
	else if(option==5)
	{
		print_symbol_table();
		int c;
		FILE *file;
		file = fopen("symbol_table_output.txt", "r");
		if (file) 
		{
    		while ((c = getc(file)) != EOF)
        		putchar(c);
    		fclose(file);
		}
		return 0;
	}
	else if(option == 6)
	{
		if(errors > 0)
	    {
	    	int i;
			for(i=0;i<errors;i++)
			{
				printf("%s",error_name[i]);
			}
	        printf("\nAbove Syntax errors are present in the code.\n");
	        //return;
	    }
	    else
	    {
	        
	        if(no_of_total_errors > 0)
	        {
	        	int i;
				for(i=0;i<no_of_total_errors;i++)
				{
					printf("%s",semantic_errors[i]);
				}
	            printf("\nAbove semantic and type checking errors are present in the code\n");
	            //return;
	        }

	        else
	        {
	            printf("Code compiles successfully..........\n");
	            //printf("Please proceed to generate ASM code\n");
	        }
	    }
	}
	else if(option==7)
	{
		if(errors==0 && no_of_total_errors==0)
		{
			int c;
			FILE *file;
			file = fopen(argv[2], "r");
			if (file) 
			{
	    		while ((c = getc(file)) != EOF)
	        		putchar(c);
	    		fclose(file);
			}
		}

		else
		{
			printf("There are syntactic and/or semantic errors. Code generation not possible.\n");
		}
	}
	else
	{
		printf("Wrong input\n");
		return 0;
	}
	return 0; 
}